language: python
dist: xenial
os: linux

matrix:
  include:
    - python: 2.7

    - python: 3.6

    - os: osx
      # Python language not available on macOS.
      # https://github.com/travis-ci/travis-ci/issues/2312
      language: generic

script: make test
